# Generated by Django 3.1.3 on 2020-11-24 02:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appraisals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=1500)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('user_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('manager_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('board_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('user_comments', models.CharField(default='NIL', max_length=2000)),
                ('manager_comments', models.CharField(default='NIL', max_length=2000)),
                ('board_comments', models.CharField(default='NIL', max_length=2000)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.user_appraisal_list')),
            ],
        ),
        migrations.CreateModel(
            name='competency_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departmental_Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.overall_appraisal')),
                ('competency_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.competency_category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.departments')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='goal_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due', models.DateField()),
                ('weightage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('metrics_Used', models.TextField(blank=True, null=True)),
                ('MID_user_comments', models.TextField(default='NIL', max_length=2000)),
                ('MID_manager_comments', models.TextField(default='NIL', max_length=2000)),
                ('user_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('manager_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('board_rating', models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1)),
                ('user_comments', models.CharField(default='NIL', max_length=2000)),
                ('manager_comments', models.CharField(default='NIL', max_length=2000)),
                ('board_comments', models.CharField(default='NIL', max_length=2000)),
                ('tracking_status', models.CharField(choices=[('null', 'null'), ('On Track', 'On Track'), ('Not On Track', 'Not On Track')], default='null', max_length=50, null=True)),
                ('metrics_evidence', models.ImageField(blank=True, null=True, upload_to='')),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.user_appraisal_list')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile')),
                ('goal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.goal_category')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(default=datetime.date.today, null=True)),
                ('progress', models.CharField(choices=[('Working', 'Working'), ('Completed', 'Completed')], default='Working', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.goals')),
            ],
        ),
        migrations.CreateModel(
            name='goal_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Departmental_Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due', models.DateField()),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.overall_appraisal')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.departments')),
                ('goal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.goal_category')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='departmental_goal_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('departmental_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.departmental_goals')),
            ],
        ),
        migrations.CreateModel(
            name='departmental_competencies_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('departmental_competencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.departmental_competencies')),
            ],
        ),
        migrations.CreateModel(
            name='competency_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.competencies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='competencies',
            name='competency_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.competency_category'),
        ),
        migrations.AddField(
            model_name='competencies',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile'),
        ),
        migrations.CreateModel(
            name='Comment_Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.goals')),
            ],
        ),
    ]
