# Generated by Django 3.0.6 on 2020-09-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0002_auto_20200816_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='summary',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='competency_category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competency_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='departmental_competencies',
            name='competency_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.competency_category'),
        ),
        migrations.AlterField(
            model_name='departmental_competencies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmental_competencies',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmental_competencies_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='departmental_goal_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='departmental_goals',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmental_goals',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='MID_manager_comments',
            field=models.TextField(default='NIL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='goals',
            name='MID_user_comments',
            field=models.TextField(default='NIL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='goals',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='metrics_Used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
