# Generated by Django 3.1.3 on 2020-11-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200815_2134'),
        ('GnC', '0003_auto_20200914_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comments', models.CharField(default='NIL', max_length=2000)),
                ('manager_comments', models.CharField(default='NIL', max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.goals')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
    ]
