# Generated by Django 3.1.3 on 2020-11-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200815_2134'),
        ('GnC', '0004_comment_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_box',
            name='manager_comments',
        ),
        migrations.RemoveField(
            model_name='comment_box',
            name='user_comments',
        ),
        migrations.RemoveField(
            model_name='comment_box',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='comment_box',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment_box',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
