# Generated by Django 3.0.6 on 2020-08-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship_Status',
            field=models.CharField(default='-', max_length=70),
        ),
    ]
